FROM golang:1.18 AS builder
WORKDIR /app
COPY echo-serv/main.go .
RUN go mod init echo-serv && go get github.com/uniqush/log && go mod tidy && go build -o echo-serv

FROM gcr.io/distroless/base-debian10
COPY --from=builder /app/echo-serv /
EXPOSE 8080
ENTRYPOINT ["/echo-serv"]